--Task 1
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Dominiak' AND TABLE_NAME = 'FACT_SALES')
   DROP TABLE Dominiak.FACT_SALES;

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Dominiak' AND TABLE_NAME = 'DIM_CUSTOMER')
   DROP TABLE Dominiak.DIM_CUSTOMER;

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Dominiak' AND TABLE_NAME = 'DIM_PRODUCT')
   DROP TABLE Dominiak.DIM_PRODUCT;

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Dominiak' AND TABLE_NAME = 'DIM_SALESPERSON')
   DROP TABLE Dominiak.DIM_SALESPERSON;

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Dominiak' AND TABLE_NAME = 'DIM_TIME')
   DROP TABLE Dominiak.DIM_TIME;

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Dominiak' AND TABLE_NAME = 'DayHelper')
   DROP TABLE Dominiak.DayHelper;

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Dominiak' AND TABLE_NAME = 'MonthHelper')
   DROP TABLE Dominiak.MonthHelper;

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'Dominiak')
   DROP SCHEMA Dominiak;
